insert into songs (Title, Artist, Genre) values ('Yesterday', 'David Bowie', 'latin');
insert into songs (Title, Artist, Genre) values ('I Want it That Way', 'Prince', 'reggae');
insert into songs (Title, Artist, Genre) values ('Imagine', 'Beyoncé', 'alternative');
insert into songs (Title, Artist, Genre) values ('Hey Ya!', 'Prince', 'r&b');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'David Bowie', 'punk');
insert into songs (Title, Artist, Genre) values ('Summer Nights', 'Prince', 'soul');
insert into songs (Title, Artist, Genre) values ('Billie Jean', 'Freddie Mercury', 'dance');
insert into songs (Title, Artist, Genre) values ('Born to Run', 'Elvis Presley', 'alternative');
insert into songs (Title, Artist, Genre) values ('Imagine', 'David Bowie', 'jazz');
insert into songs (Title, Artist, Genre) values ('Waterloo', 'Beyoncé', 'latin');
insert into songs (Title, Artist, Genre) values ('Karma Chameleon', 'Bob Dylan', 'punk');
insert into songs (Title, Artist, Genre) values ('Purple Rain', 'Elvis Presley', 'punk');
insert into songs (Title, Artist, Genre) values ('Don''t You Want Me', 'John Lennon', 'gospel');
insert into songs (Title, Artist, Genre) values ('Purple Rain', 'Bob Dylan', 'country');
insert into songs (Title, Artist, Genre) values ('Like a Rolling Stone', 'John Lennon', 'classical');
insert into songs (Title, Artist, Genre) values ('Like a Rolling Stone', 'Taylor Swift', 'country');
insert into songs (Title, Artist, Genre) values ('Billie Jean', 'Beyoncé', 'pop');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'Prince', 'indie');
insert into songs (Title, Artist, Genre) values ('Purple Rain', 'Prince', 'pop');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Beyoncé', 'dance');
insert into songs (Title, Artist, Genre) values ('Midnight Memories', 'Prince', 'jazz');
insert into songs (Title, Artist, Genre) values ('Hey Ya!', 'Michael Jackson', 'soul');
insert into songs (Title, Artist, Genre) values ('I Will Always Love You', 'Prince', 'rock');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Beyoncé', 'dance');
insert into songs (Title, Artist, Genre) values ('Sweet Escape', 'David Bowie', 'punk');
insert into songs (Title, Artist, Genre) values ('I Wanna Dance with Somebody', 'John Lennon', 'folk');
insert into songs (Title, Artist, Genre) values ('Shape of You', 'Bob Dylan', 'jazz');
insert into songs (Title, Artist, Genre) values ('I Want to Hold Your Hand', 'Michael Jackson', 'metal');
insert into songs (Title, Artist, Genre) values ('I Want it That Way', 'John Lennon', 'r&b');
insert into songs (Title, Artist, Genre) values ('I Want it That Way', 'Bob Dylan', 'indie');
insert into songs (Title, Artist, Genre) values ('Yesterday', 'John Lennon', 'folk');
insert into songs (Title, Artist, Genre) values ('Every Breath You Take', 'David Bowie', 'metal');
insert into songs (Title, Artist, Genre) values ('Livin'' La Vida Loca', 'Elvis Presley', 'classical');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Freddie Mercury', 'reggae');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'David Bowie', 'funk');
insert into songs (Title, Artist, Genre) values ('Sweet Escape', 'Madonna', 'blues');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'David Bowie', 'funk');
insert into songs (Title, Artist, Genre) values ('Don''t You Want Me', 'Taylor Swift', 'classical');
insert into songs (Title, Artist, Genre) values ('Boogie Wonderland', 'Elvis Presley', 'jazz');
insert into songs (Title, Artist, Genre) values ('Eye of the Tiger', 'Elvis Presley', 'blues');
insert into songs (Title, Artist, Genre) values ('I Wanna Dance with Somebody', 'Freddie Mercury', 'country');
insert into songs (Title, Artist, Genre) values ('Crazy in Love', 'David Bowie', 'gospel');
insert into songs (Title, Artist, Genre) values ('I Will Always Love You', 'Madonna', 'soul');
insert into songs (Title, Artist, Genre) values ('Born to Run', 'Freddie Mercury', 'pop');
insert into songs (Title, Artist, Genre) values ('Take on Me', 'Prince', 'blues');
insert into songs (Title, Artist, Genre) values ('Waterloo', 'David Bowie', 'reggae');
insert into songs (Title, Artist, Genre) values ('I Want it That Way', 'Elvis Presley', 'pop');
insert into songs (Title, Artist, Genre) values ('I Want to Hold Your Hand', 'Beyoncé', 'latin');
insert into songs (Title, Artist, Genre) values ('I Want it That Way', 'Michael Jackson', 'gospel');
insert into songs (Title, Artist, Genre) values ('I Wanna Dance with Somebody', 'Madonna', 'gospel');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Madonna', 'reggae');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Bob Dylan', 'pop');
insert into songs (Title, Artist, Genre) values ('Don''t You Want Me', 'Prince', 'country');
insert into songs (Title, Artist, Genre) values ('Don''t Stop Me Now', 'Prince', 'funk');
insert into songs (Title, Artist, Genre) values ('Take on Me', 'John Lennon', 'country');
insert into songs (Title, Artist, Genre) values ('Midnight Memories', 'David Bowie', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Take on Me', 'Beyoncé', 'blues');
insert into songs (Title, Artist, Genre) values ('Rolling in the Deep', 'Prince', 'rock');
insert into songs (Title, Artist, Genre) values ('Crazy in Love', 'Elvis Presley', 'reggae');
insert into songs (Title, Artist, Genre) values ('Sweet Escape', 'Elvis Presley', 'alternative');
insert into songs (Title, Artist, Genre) values ('Livin'' on a Prayer', 'Prince', 'alternative');
insert into songs (Title, Artist, Genre) values ('Livin'' on a Prayer', 'Prince', 'indie');
insert into songs (Title, Artist, Genre) values ('Uptown Funk', 'Elvis Presley', 'blues');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Elvis Presley', 'folk');
insert into songs (Title, Artist, Genre) values ('Rolling in the Deep', 'John Lennon', 'r&b');
insert into songs (Title, Artist, Genre) values ('Take on Me', 'Bob Dylan', 'blues');
insert into songs (Title, Artist, Genre) values ('I Will Always Love You', 'Beyoncé', 'folk');
insert into songs (Title, Artist, Genre) values ('Livin'' on a Prayer', 'Madonna', 'pop');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Prince', 'electronic');
insert into songs (Title, Artist, Genre) values ('I Want it That Way', 'Elvis Presley', 'r&b');
insert into songs (Title, Artist, Genre) values ('I Will Survive', 'David Bowie', 'pop');
insert into songs (Title, Artist, Genre) values ('I Want it That Way', 'Madonna', 'pop');
insert into songs (Title, Artist, Genre) values ('Crazy in Love', 'Beyoncé', 'jazz');
insert into songs (Title, Artist, Genre) values ('Livin'' on a Prayer', 'Prince', 'alternative');
insert into songs (Title, Artist, Genre) values ('Eye of the Tiger', 'Michael Jackson', 'alternative');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Prince', 'country');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'David Bowie', 'metal');
insert into songs (Title, Artist, Genre) values ('Thriller', 'Taylor Swift', 'electronic');
insert into songs (Title, Artist, Genre) values ('Imagine', 'Bob Dylan', 'metal');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'John Lennon', 'classical');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'Freddie Mercury', 'reggae');
insert into songs (Title, Artist, Genre) values ('Shape of You', 'Freddie Mercury', 'jazz');
insert into songs (Title, Artist, Genre) values ('Summer Nights', 'Taylor Swift', 'classical');
insert into songs (Title, Artist, Genre) values ('Don''t You Want Me', 'Bob Dylan', 'gospel');
insert into songs (Title, Artist, Genre) values ('Karma Chameleon', 'Freddie Mercury', 'electronic');
insert into songs (Title, Artist, Genre) values ('I Will Survive', 'Beyoncé', 'classical');
insert into songs (Title, Artist, Genre) values ('Rolling in the Deep', 'Elvis Presley', 'jazz');
insert into songs (Title, Artist, Genre) values ('Purple Rain', 'John Lennon', 'rock');
insert into songs (Title, Artist, Genre) values ('Summer Nights', 'Elvis Presley', 'indie');
insert into songs (Title, Artist, Genre) values ('I Wanna Dance with Somebody', 'Michael Jackson', 'funk');
insert into songs (Title, Artist, Genre) values ('Sweet Escape', 'Bob Dylan', 'dance');
insert into songs (Title, Artist, Genre) values ('Billie Jean', 'John Lennon', 'hip hop');
insert into songs (Title, Artist, Genre) values ('I Want it That Way', 'Michael Jackson', 'indie');
insert into songs (Title, Artist, Genre) values ('Hey Ya!', 'Beyoncé', 'funk');
insert into songs (Title, Artist, Genre) values ('Waterloo', 'Madonna', 'r&b');
insert into songs (Title, Artist, Genre) values ('Livin'' La Vida Loca', 'Taylor Swift', 'metal');
insert into songs (Title, Artist, Genre) values ('Crazy in Love', 'Prince', 'dance');
insert into songs (Title, Artist, Genre) values ('Wannabe', 'Michael Jackson', 'electronic');
insert into songs (Title, Artist, Genre) values ('Sweet Escape', 'Taylor Swift', 'pop');
insert into songs (Title, Artist, Genre) values ('Thriller', 'Michael Jackson', 'dance');
